### Useful for this file
### https://manpages.ubuntu.com/manpages/jammy/man5/smb.conf.5.html
### https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html
### 
### Pay attention to
### https://manpages.ubuntu.com/manpages/jammy/man5/smb.conf.5.html#warnings

import re
import hashlib
import os
import shlex
import io
import configparser
import logging
from textwrap import dedent
from dataclasses import dataclass, field

from .ShellScript import ShellScript
from . import terminal, utils
from gi.repository import GLib  # noqa


@dataclass
class WarningEntry:
    title: str
    description: str

@dataclass
class SambaShare:
    name: str
    share_path: str
    comment: str
    writeable: bool
    public: bool
    valid_users: list = field(default_factory=list)
    force_user: str | None = None

    @staticmethod
    def create_empty():
        return SambaShare(
            name='',
            share_path='',
            comment='',
            writeable=True,
            public=True,
            valid_users=[],
            force_user=None
        )
    
@dataclass
class SambaUser:
    user: str
    uid: str
    comment: str

class SambaConfig():
    DEFAULT_SECTION = 'global'
    DEFAULT_GLOBAL_SECTION = {
        'workgroup': 'WORKGROUP',
        'netbios name': '',
        'server string': '%h server (Samba)',
        'server role': 'standalone server',
        'log file': '/var/log/samba/log.%J',
        'max log size': '1000',
        'logging': 'file',
        'map to guest': 'bad user',
        # Keep samba and unix users separated, makes everything easier
        'unix password sync': 'no',
        'pam password change': 'no',
        # Disable usershare to keep everything under control
        'usershare max shares': '0',
        'passwd chat': '"new password" %n\\n "retype new password" %n\\n "Password changed"'
    }
    REQUIRED_CLI_TOOLS = ['testparm', 'smbd', 'smbcontrol', 'smbstatus']
    RESERVED_SECTIONS = ['homes', 'printers', 'global', 'print$']
    COMMENTS_LINE_START = ['#', ';']
    REQUIRED_HEADER_LINE = '# - This configuration file was automatically generated by Simba -'
    CONFIG_FILE_HEADER = """
        #
        # - This configuration file was automatically generated by Simba -
        # A GUI tool to manage the Samba server.
        #
        # For addiitonal information about smb.com, please visit the following website:
        # https://www.samba.org/samba/docs/current/man-html/smb.conf.5.html
        #
        # For addiitonal information about Simba, please visit the following website:
        # https://github.com/mijorus/simba
        #
        #
        # If you still want to manager your server using Simba, 
        # do not remove the following lines.
        #
        # Hash: $file_hash
        #
    """

    def __init__(self, override_config_file_location=None) -> None:
        self.config_file_location = utils.mapped_path('/etc/samba/smb.conf')
        self.sys_config_file_location = self.config_file_location
        self.tmp_config_file_location = GLib.get_user_cache_dir()
        self.service_name = 'smb.service'

        if override_config_file_location:
            self.config_file_location = override_config_file_location

        self._config_file_content = ''
        self.data = configparser.ConfigParser(
            comment_prefixes=self.COMMENTS_LINE_START,
            inline_comment_prefixes=self.COMMENTS_LINE_START,
            strict=True,
            interpolation=None,
            default_section=self.DEFAULT_SECTION
        )

        for s in ['smb.service', 'smbd.service']:
            try:
                terminal.host_sh(['systemctl', 'list-unit-files', s])
                self.service_name = s
                break

            except Exception as e:
                pass

        if os.path.exists(self.config_file_location):
            self._parse()

    @staticmethod
    def get_samba_version():
        smbv = terminal.host_sh(['smbd', '--version'])
        return smbv.replace('Version', '').strip().split('.')

    @staticmethod
    def test_compatibility():
        for tool in SambaConfig.REQUIRED_CLI_TOOLS:
            try:
                terminal.host_sh(['command', '-v', tool])
            except Exception as e:
                logging.warning('Missing required CLI tool: ' + tool)
                return False
        
        if SambaConfig.get_samba_version()[0] != '4':
            return False
        
        smbservice = False
        for s in ['smb.service', 'smbd.service']:
            try:
                terminal.host_sh(['systemctl', 'list-unit-files', s])
                smbservice = True
            except Exception as e:
                pass
        
        if not smbservice:
            return False

        return True

    @staticmethod
    def scan_warnings():
        _warnings: list[WarningEntry] = []

        try:
            terminal.host_sh(['which', 'getsebool'])
            se_resp = terminal.host_sh(['getsebool', 'samba_enable_home_dirs'])
            print(se_resp)
            if se_resp.endswith('> off'):
                _warnings.append(WarningEntry(
                    title=_('SELinux'),
                    description=_('SELinux policy "samba_enable_home_dirs" is off, this might cause issues when trying to share folder in your home directory')
                ))
        except Exception as e:
            pass

        return _warnings

    def is_config_supported(self):
        if self.REQUIRED_HEADER_LINE not in self._config_file_content:
            logging.warning('required header line not found')
            return False

        pattern = r'# Hash:\s*([a-fA-F0-9]{32})'
        match = re.search(pattern, self._config_file_content, re.MULTILINE)

        if not match:
            logging.warning('hash not found')
            return False

        stored_hash = match.group(1)
        current_hash = self.get_md5(file_path=self.config_file_location)

        if stored_hash != current_hash:
            logging.warning('hash do not match:')

        return stored_hash == current_hash

    def init_with_defaults(self):
        self.data.clear(    )
        self.data['global'] = self.DEFAULT_GLOBAL_SECTION

    def save(self):
        text_content = self._get_text_content()

        random_string = utils.get_random_md5()
        testfile_path = os.path.join(self.tmp_config_file_location, f'{random_string}.conf')
        config_file_hash = self.get_md5(content=text_content)
        text_header = dedent(self.CONFIG_FILE_HEADER).replace('$file_hash', config_file_hash)
        text_content = '\n'.join([text_header, text_content])

        with open(testfile_path, 'w+') as f:
            f.write(text_content)

        # check file validity
        terminal.host_sh(['testparm', '--suppress-prompt', testfile_path])

        save_script = ShellScript(
            filename='save_samba_config.sh',
            content="""
                set -e
                cp $location $location_old
                cp $testfile_path $location
                systemctl restart $service
            """,
            testfile_path=testfile_path,
            service=self.service_name,
            location=self.sys_config_file_location,
            location_old=f'{self.sys_config_file_location}.simba.old'
        )

        save_script.root_host_execute()

        if os.path.exists(testfile_path):
            os.remove(testfile_path)

        save_script.delete()
        self._parse()

    def get_md5(self, file_path=None, content=''):
        if (not content) and (not file_path):
            raise Exception('Missing content and file_path')

        if file_path:
            with open(file_path, 'r') as f:
                content = f.read()

        valid_content = ''
        for line in content.split('\n'):
            skip_line = False
            line = line.strip()
            for s in self.COMMENTS_LINE_START:
                skip_line = (not line) or line.startswith(s)
                
                if skip_line:
                    break
            
            if not skip_line:
                valid_content += (line + '\n')

        filehash = hashlib.md5(valid_content.encode()).hexdigest()

        return filehash

    def get_section(self, section: str):
        return self.data[section]
    
    def create_section(self, section: str, data: dict):
        self.data[section] = data

    def check_valid_share_name(self, name: str) -> tuple:
        if name in self.RESERVED_SECTIONS:
            return (False, 'name reserved')
        
        if len(name) > 8:
            return (False, 'name is too long')
        
        return (True, '')

    def delete_share(self, share: SambaShare):
        if share.name not in self.data.keys():
            raise Exception(f'{share.name} does not exists! Available shares are: {self.data.keys()}')
        
        del self.data[share.name]

    def create_share(self, share: SambaShare):
        name_check, name_check_error = self.check_valid_share_name(share.name)
        if not name_check:
            raise Exception(f'{share.name}: ' + name_check_error)
        
        section_content = {
            'path': share.share_path,
            'writeable': self._bool_value(share.writeable),
            'public': self._bool_value(share.public),
            'comment': share.comment,

            # MacOS stuff
            'veto files': '/.DS_Store/._.*/',
            'delete veto files': self._bool_value(True)
        }

        if share.force_user:
            section_content['force user'] = share.force_user

        self.create_section(share.name, section_content)

    def _bool_value(self, val: bool):
        return 'yes' if val else 'no'

    def list_shares(self) -> list[SambaShare]:
        shares = []
        for section, data in self.data.items():
            if f'{section}' in self.RESERVED_SECTIONS:
                continue

            writeable = data.getboolean('writeable', True)

            share = SambaShare(
                name=section,
                share_path=data.get('path', ''),
                comment=data.get('comment', ''),
                writeable=writeable,
                public=data.getboolean('public', True),
                force_user=data.get('force user', None)
            )

            shares.append(share)

        return shares

    @staticmethod
    def create_user(user, passwd):
        pass_str = f'{passwd}\\n{passwd}\\n'
        ShellScript(
            filename='create_samba_user.sh',
            content="""
                set -e
                echo -ne $passwd | pdbedit --create --password-from-stdin $user
            """,
            passwd=pass_str,
            user=user
        ).root_host_execute()

    @staticmethod
    def list_users() -> list[SambaUser]:
        data = terminal.host_sh(['pkexec', 'pdbedit', '--list'], hide_log=True)
        data = data.strip()
        output = []

        for line in data.split('\n'):
            spl = line.split(':')

            if len(spl) < 3:
                continue

            u, uid, comment = line.split(':')
            user = SambaUser(user=u, uid=uid, comment=comment)
            output.append(user)

        return output


    def _get_text_content(self):
        # 1. Create the string buffer
        string_stream = io.StringIO()

        # 2. Write the config object into the buffer
        self.data.write(string_stream)

        # 3. Retrieve the string value
        config_string = string_stream.getvalue()
        return config_string

    def _parse(self):
        """Parse a smb file"""
        with open(self.config_file_location, 'r') as f:
            self._config_file_content = f.read()

        self.data.read(self.config_file_location)
